//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.DFAssist.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.DFAssist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _061809 {
            get {
                object obj = ResourceManager.GetObject("061809", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap annotation {
            get {
                object obj = ResourceManager.GetObject("annotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btn_del {
            get {
                object obj = ResourceManager.GetObject("btn_del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {
        ///    &quot;roulettes&quot;: {
        ///        &quot;1&quot;: &quot;Zufallsinhalt: Stufensteigerung&quot;,
        ///        &quot;2&quot;: &quot;Zufallsinhalt: Stufe 50/60/70&quot;,
        ///        &quot;3&quot;: &quot;Zufallsinhalt: Hauptszenario&quot;,
        ///        &quot;4&quot;: &quot;Zufallsinhalt: Gildengeheiß&quot;,
        ///        &quot;5&quot;: &quot;Zufallsinhalt: Experte&quot;,
        ///        &quot;6&quot;: &quot;Zufallsinhalt: Prüfung&quot;,
        ///        &quot;7&quot;: &quot;Zufallsinhalt: PvP-Front&quot;,
        ///        &quot;8&quot;: &quot;Zufallsinhalt: Stufe 80&quot;,
        ///        &quot;9&quot;: &quot;Zufallsinhalt: Mentor&quot;,
        ///        &quot;10&quot;: &quot;The Feast (Übungskampf)&quot;,
        ///        &quot;11&quot;: &quot;The Feast (Übungskampf)&quot;,
        ///        &quot;13&quot;: &quot;The Feast (gew[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dfas_de {
            get {
                return ResourceManager.GetString("dfas_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///    &quot;roulettes&quot;: {
        ///        &quot;1&quot;: &quot;Duty Roulette: Leveling&quot;,
        ///        &quot;2&quot;: &quot;Duty Roulette: Level 50/60/70 Dungeons&quot;,
        ///        &quot;3&quot;: &quot;Duty Roulette: Main Scenario&quot;,
        ///        &quot;4&quot;: &quot;Duty Roulette: Guildhests&quot;,
        ///        &quot;5&quot;: &quot;Duty Roulette: Expert&quot;,
        ///        &quot;6&quot;: &quot;Duty Roulette: Trials&quot;,
        ///        &quot;7&quot;: &quot;Duty Roulette: Frontline&quot;,
        ///        &quot;8&quot;: &quot;Duty Roulette: Level 80 Dungeons&quot;,
        ///        &quot;9&quot;: &quot;Duty Roulette: Mentor&quot;,
        ///        &quot;10&quot;: &quot;The Feast - Training&quot;,
        ///        &quot;11&quot;: &quot;The Feast - Training&quot;,
        ///        &quot;13&quot;: &quot;The Feast - Ra[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dfas_en {
            get {
                return ResourceManager.GetString("dfas_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///    &quot;roulettes&quot;: {
        ///        &quot;1&quot;: &quot;Mission aléatorie: gain de niveaux&quot;,
        ///        &quot;2&quot;: &quot;Mission aléatorie: donjons nv 50/60/70&quot;,
        ///        &quot;3&quot;: &quot;Mission aléatorie: épopée&quot;,
        ///        &quot;4&quot;: &quot;Mission aléatorie: opérations de guilde&quot;,
        ///        &quot;5&quot;: &quot;Mission aléatorie: expert&quot;,
        ///        &quot;6&quot;: &quot;Mission aléatorie: défis&quot;,
        ///        &quot;7&quot;: &quot;Mission aléatorie: Front&quot;,
        ///        &quot;8&quot;: &quot;Mission aléatorie: donjons nv 80&quot;,
        ///        &quot;9&quot;: &quot;Mission aléatorie: Mentor&quot;,
        ///        &quot;10&quot;: &quot;The Feast (entraînement)&quot;,
        ///        &quot;11&quot;: &quot;The Feast (entr[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dfas_fr {
            get {
                return ResourceManager.GetString("dfas_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///    &quot;roulettes&quot;: {
        ///        &quot;1&quot;: &quot;コンテンツルーレット: レベリング&quot;,
        ///        &quot;2&quot;: &quot;コンテンツルーレット: レベル50・60・70ダンジョン&quot;,
        ///        &quot;3&quot;: &quot;コンテンツルーレット: メインクエスト&quot;,
        ///        &quot;4&quot;: &quot;コンテンツルーレット: ギルドオーダー&quot;,
        ///        &quot;5&quot;: &quot;コンテンツルーレット: エキスパート&quot;,
        ///        &quot;6&quot;: &quot;コンテンツルーレット: 討伐・討滅戦&quot;,
        ///        &quot;7&quot;: &quot;コンテンツルーレット: フロントライン&quot;,
        ///        &quot;8&quot;: &quot;コンテンツルーレット: レベル80ダンジョン&quot;,
        ///        &quot;9&quot;: &quot;コンテンツルーレット: メンター&quot;,
        ///        &quot;10&quot;: &quot;ザ・フィースト (カジュアルマッチ)&quot;,
        ///        &quot;11&quot;: &quot;ザ・フィースト (カジュアルマッチ)&quot;,
        ///        &quot;13&quot;: &quot;ザ・フィースト (ランクマッチ)&quot;,
        ///        &quot;15&quot;: &quot;コンテンツルーレット: アライアンスレイド&quot;,
        ///        &quot;16&quot;: &quot;ザ・[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dfas_ja {
            get {
                return ResourceManager.GetString("dfas_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///    &quot;roulettes&quot;: {
        ///        &quot;1&quot;: &quot;무작위 임무: 레벨링&quot;,
        ///        &quot;2&quot;: &quot;무작위 임무: 레벨 50/60/70 던전&quot;,
        ///        &quot;3&quot;: &quot;무작위 임무: 주요 퀘스트&quot;,
        ///        &quot;4&quot;: &quot;무작위 임무: 길드 작전&quot;,
        ///        &quot;5&quot;: &quot;무작위 임무: 숙련자&quot;,
        ///        &quot;6&quot;: &quot;무작위 임무: 토벌전&quot;,
        ///        &quot;7&quot;: &quot;무작위 임무: 전장&quot;,
        ///        &quot;8&quot;: &quot;무작위 임무: 레벨 80 던전&quot;,
        ///        &quot;9&quot;: &quot;무작위 임무: 멘토&quot;,
        ///        &quot;10&quot;: &quot;더 피스트 - 친선 경기&quot;,
        ///        &quot;11&quot;: &quot;더 피스트 - 친선 경기&quot;,
        ///        &quot;13&quot;: &quot;더 피스트 - 개인&quot;,
        ///        &quot;15&quot;: &quot;무작위 임무: 24인 레이드&quot;,
        ///        &quot;16&quot;: &quot;더 피스트 - 팀&quot;,
        ///        &quot;17&quot;: &quot;무작위 임무: 레이드&quot;,
        ///        &quot;18&quot;: &quot;초코보 레이스: 사골리길&quot;,
        ///        &quot;1[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dfas_ko {
            get {
                return ResourceManager.GetString("dfas_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap magnifyingglassicon_114513_22 {
            get {
                object obj = ResourceManager.GetObject("magnifyingglassicon_114513-22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Main_Command_52_Icon {
            get {
                object obj = ResourceManager.GetObject("Main_Command_52_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Map64_Icon {
            get {
                object obj = ResourceManager.GetObject("Map64_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   # ACT.DFAssist english message
        ///
        ///app-description=DFASSIST for ACT
        ///app-name=DFASSIST
        ///e-setting-load=Error on reading settings: {0}
        ///e-setting-save=Error on saving settings
        ///e-null-data=Null data found: {0}
        ///i-data-version=Read game data (R:{2}/I:{1}/A:{0}/F:{3})
        ///i-matched=Matched [{0}]
        ///i-queue-instance=Start matching [{0}]
        ///i-queue-roulette=Start roulette matching [{0}]
        ///i-selected-color=Selected color is {0}
        ///l-data-error=Error on processing data
        ///l-fate-occured-info=\&quot;{0}\&quot; spawned!
        ///l-instance-enter=[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mesg_en {
            get {
                return ResourceManager.GetString("mesg_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # ACT.DFAssist にほんご メッセージ
        ///
        ///app-description=ACT用のDFASSISTプラグイン
        ///app-name=DFASSIST
        ///e-setting-load=設定読みにエラー: {0}
        ///e-setting-save=設定保存にエラー
        ///e-null-data=空きデータが見つかりました: {0}
        ///i-data-version=データを読みました (A:{0}/I:{1}/R:{2}/F:{3})
        ///i-matched=準備完了 [{0}]
        ///i-queue-instance=コンテンツ参加申請開始 [{0}]
        ///i-queue-roulette=ルーレット参加申請開始 [{0}]
        ///i-selected-color=選択した色は{0}です
        ///l-data-error= データ処理に問題があります
        ///l-fate-occured-info=\&quot;{0}\&quot; 発生!
        ///l-instance-enter=Instance: 入ります: {0}
        ///l-instance-leave=Instance: 離れます
        ///l-plugin-started=プラグイン開始
        ///l-plug[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mesg_ja {
            get {
                return ResourceManager.GetString("mesg_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # ACT.DFAssist 한국어 메시지
        ///
        ///app-description=ACT에서 쓸 수 있는 DFASSIST 플러그인
        ///app-name=DFASSIST
        ///e-setting-load=설정 읽기 오류: {0}
        ///e-setting-save=설정 저장 오류
        ///e-null-data=빈값이 있습니다: {0}
        ///i-data-version=데이터를 읽었습니다 (A:{0}/I:{1}/R:{2}/F:{3})
        ///i-matched=Queue: 매치 잡힘 [{0}]
        ///i-queue-instance=매치 시작 [{0}]
        ///i-queue-roulette=루렛 시작 [{0}]
        ///i-selected-color=선택한 색깔은 {0}입니다
        ///l-data-error=데이터 처리에 문제가 있습니다
        ///l-fate-occured-info=\&quot;{0}\&quot; 떳다!
        ///l-instance-enter=인스턴스 들어감: {0}
        ///l-instance-leave=인스턴스 나옴
        ///l-plugin-started=플러그인 시작
        ///l-plugin-stopped=[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mesg_ko {
            get {
                return ResourceManager.GetString("mesg_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Player12_Icon {
            get {
                object obj = ResourceManager.GetObject("Player12_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Player2_Icon {
            get {
                object obj = ResourceManager.GetObject("Player2_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
