//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.DFAssist.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.DFAssist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _061809 {
            get {
                object obj = ResourceManager.GetObject("061809", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap annotation {
            get {
                object obj = ResourceManager.GetObject("annotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btn_del {
            get {
                object obj = ResourceManager.GetObject("btn_del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {
        ///  // Data from Jaehyuk-Lee/DFASSIST
        ///  // Version
        ///  &quot;version&quot;: &quot;202001101.4&quot;,
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;Sastasha&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;Brüllvolx&apos; Langrast&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;Palast des Wanderers&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string gamedata_de {
            get {
                return ResourceManager.GetString("gamedata_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  // Version
        ///  &quot;version&quot;: &quot;202001101.1&quot;,
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;Sastasha&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;Brayflox&apos;s Longstop&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;The Wanderer&apos;s Palace&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;Copperbell Min[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string gamedata_en {
            get {
                return ResourceManager.GetString("gamedata_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  // Data from Jaehyuk-Lee/DFASSIST
        ///  // Version
        ///  &quot;version&quot;: &quot;202001101.5&quot;,
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;Sastasha&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;le Bivouac de Brayflox&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;le Palais du Vagabond&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        /// [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string gamedata_fr {
            get {
                return ResourceManager.GetString("gamedata_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  // Version
        ///  &quot;version&quot;: &quot;202001101.2&quot;,
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;天然要害 サスタシャ浸食洞&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;奪還支援 ブレイフロクスの野営地&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;旅神聖域 ワンダラーパレス&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;封鎖坑道 カッパーベル銅山&quot;,
        ///   [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string gamedata_ja {
            get {
                return ResourceManager.GetString("gamedata_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  // Version
        ///  &quot;version&quot;: &quot;202001101.3&quot;,
        ///
        ///  // 임무
        ///  &quot;instances&quot;: {
        ///    // 2.0 신생 에오르제아
        ///    // 2.0 던전
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;사스타샤 침식 동굴&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;브레이플록스의 야영지&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;방랑자의 궁전&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;구리종 광산&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string gamedata_ko {
            get {
                return ResourceManager.GetString("gamedata_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;app-description&quot;: &quot;DFASSIST for ACT&quot;,
        ///  &quot;app-name&quot;: &quot;DFASSIST&quot;,
        ///  &quot;l-data-error&quot;: &quot;Error on processing data&quot;,
        ///  &quot;l-fate-occured-info&quot;: &quot;{0} spawned!&quot;,
        ///  &quot;l-instance-enter&quot;: &quot;Enter instance: {0}&quot;,
        ///  &quot;l-instance-leave&quot;: &quot;Leave instance&quot;,
        ///  &quot;i-selected-color&quot;: &quot;Selected color is {0}&quot;,
        ///  &quot;i-data-version&quot;: &quot;Using data version {0} (A:{1}/I:{2}/R:{3}/F:{4})&quot;,
        ///  &quot;l-plugin-started&quot;: &quot;Plugin started&quot;,
        ///  &quot;l-plugin-stopped&quot;: &quot;Plugin stopped&quot;,
        ///  &quot;i-matched&quot;: &quot;Matched [{0}]&quot;,
        ///  &quot;i-queue-instance&quot;: &quot;Start matching [{[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string locale_en {
            get {
                return ResourceManager.GetString("locale_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;app-description&quot;: &quot;ACT用のDFASSISTプラグイン&quot;,
        ///  &quot;app-name&quot;: &quot;DFASSIST&quot;,
        ///  &quot;l-analyze-error&quot;: &quot;Analyze: メッセージ処理エラー&quot;,
        ///  &quot;l-analyze-error-general&quot;: &quot;Analyze: メッセージ分析エラー&quot;,
        ///  &quot;l-analyze-error-handle&quot;: &quot;Analyze: メッセージ分析エラー&quot;,
        ///  &quot;l-analyze-error-length&quot;: &quot;Analyze: メッセージ長さエラー: {0}, {1}/{2}&quot;,
        ///  &quot;l-assembly-load-error&quot;: &quot;アセンブリの読むことが出来ません: {0}&quot;,
        ///  &quot;l-data-error&quot;: &quot;Data: データ処理に問題があります&quot;,
        ///  &quot;l-fate-occured-info&quot;: &quot;FATE: {0} 発生!&quot;,
        ///  &quot;l-field-instance-entered&quot;: &quot;Instance: 入ります: {0}&quot;,
        ///  &quot;l-field-instance-left&quot;: &quot;Instance: 離れま[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string locale_ja {
            get {
                return ResourceManager.GetString("locale_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;app-description&quot;: &quot;ACT에서 쓸 수 있는 DFASSIST 플러그인&quot;,
        ///  &quot;app-name&quot;: &quot;DFASSIST&quot;,
        ///  &quot;l-analyze-error&quot;: &quot;Analyze: 메시지 처리 오류&quot;,
        ///  &quot;l-analyze-error-general&quot;: &quot;Analyze: 메시지 분석 오류&quot;,
        ///  &quot;l-analyze-error-handle&quot;: &quot;Analyze: 메시지 핸들링 오류&quot;,
        ///  &quot;l-analyze-error-length&quot;: &quot;Analyze: 메시지 길이 오류: {0}, {1}/{2}&quot;,
        ///  &quot;l-assembly-load-error&quot;: &quot;어셈블리를 읽을 수 없습니다: {0}&quot;,
        ///  &quot;l-data-error&quot;: &quot;Data: 데이터 처리에 문제가 있습니다&quot;,
        ///  &quot;l-fate-occured-info&quot;: &quot;FATE: {0} 떳다!&quot;,
        ///  &quot;l-field-instance-entered&quot;: &quot;Instance: 들어감: {0}&quot;,
        ///  &quot;l-field-instance-left&quot;: &quot;Instanc[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string locale_ko {
            get {
                return ResourceManager.GetString("locale_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap magnifyingglassicon_114513_22 {
            get {
                object obj = ResourceManager.GetObject("magnifyingglassicon_114513-22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Main_Command_52_Icon {
            get {
                object obj = ResourceManager.GetObject("Main_Command_52_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Map64_Icon {
            get {
                object obj = ResourceManager.GetObject("Map64_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Player12_Icon {
            get {
                object obj = ResourceManager.GetObject("Player12_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Player2_Icon {
            get {
                object obj = ResourceManager.GetObject("Player2_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
