//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.DFAssist.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.DFAssist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _061809 {
            get {
                object obj = ResourceManager.GetObject("061809", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap annotation {
            get {
                object obj = ResourceManager.GetObject("annotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_del {
            get {
                object obj = ResourceManager.GetObject("btn_del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;roulettes&quot;: {
        ///        &quot;1&quot;: &quot;Zufallsinhalt: Stufensteigerung&quot;,
        ///        &quot;2&quot;: &quot;Zufallsinhalt: Stufe 50/60/70&quot;,
        ///        &quot;3&quot;: &quot;Zufallsinhalt: Hauptszenario&quot;,
        ///        &quot;4&quot;: &quot;Zufallsinhalt: Gildengeheiß&quot;,
        ///        &quot;5&quot;: &quot;Zufallsinhalt: Experte&quot;,
        ///        &quot;6&quot;: &quot;Zufallsinhalt: Prüfung&quot;,
        ///        &quot;7&quot;: &quot;Zufallsinhalt: PvP-Front&quot;,
        ///        &quot;8&quot;: &quot;Zufallsinhalt: Stufe 80&quot;,
        ///        &quot;9&quot;: &quot;Zufallsinhalt: Mentor&quot;,
        ///        &quot;10&quot;: &quot;The Feast (Übungskampf)&quot;,
        ///        &quot;11&quot;: &quot;The Feast (Übungskampf)&quot;,
        ///        &quot;13&quot;: &quot;The Feast (gew [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dfas_de {
            get {
                return ResourceManager.GetString("dfas_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;roulettes&quot;: {
        ///    &quot;1&quot;: &quot;Duty Roulette: Leveling&quot;,
        ///    &quot;2&quot;: &quot;Duty Roulette: Level 50/60/70 Dungeons&quot;,
        ///    &quot;3&quot;: &quot;Duty Roulette: Main Scenario&quot;,
        ///    &quot;4&quot;: &quot;Duty Roulette: Guildhests&quot;,
        ///    &quot;5&quot;: &quot;Duty Roulette: Expert&quot;,
        ///    &quot;6&quot;: &quot;Duty Roulette: Trials&quot;,
        ///    &quot;7&quot;: &quot;Duty Roulette: Frontline&quot;,
        ///    &quot;8&quot;: &quot;Duty Roulette: Level 80 Dungeons&quot;,
        ///    &quot;9&quot;: &quot;Duty Roulette: Mentor&quot;,
        ///    &quot;10&quot;: &quot;The Feast - Training&quot;,
        ///    &quot;11&quot;: &quot;The Feast - Training&quot;,
        ///    &quot;13&quot;: &quot;The Feast - Ranked&quot;,
        ///    &quot;15&quot;: &quot;Duty Roulette: Alliance Raids&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dfas_en {
            get {
                return ResourceManager.GetString("dfas_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;roulettes&quot;: {
        ///    &quot;1&quot;: &quot;Mission aléatorie: gain de niveaux&quot;,
        ///    &quot;2&quot;: &quot;Mission aléatorie: donjons nv 50/60/70&quot;,
        ///    &quot;3&quot;: &quot;Mission aléatorie: épopée&quot;,
        ///    &quot;4&quot;: &quot;Mission aléatorie: opérations de guilde&quot;,
        ///    &quot;5&quot;: &quot;Mission aléatorie: expert&quot;,
        ///    &quot;6&quot;: &quot;Mission aléatorie: défis&quot;,
        ///    &quot;7&quot;: &quot;Mission aléatorie: Front&quot;,
        ///    &quot;8&quot;: &quot;Mission aléatorie: donjons nv 80&quot;,
        ///    &quot;9&quot;: &quot;Mission aléatorie: Mentor&quot;,
        ///    &quot;10&quot;: &quot;The Feast (entraînement)&quot;,
        ///    &quot;11&quot;: &quot;The Feast (entraînement)&quot;,
        ///    &quot;13&quot;: &quot;The Feast (classé)&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dfas_fr {
            get {
                return ResourceManager.GetString("dfas_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;roulettes&quot;: {
        ///    &quot;1&quot;: &quot;コンテンツルーレット: レベリング&quot;,
        ///    &quot;2&quot;: &quot;コンテンツルーレット: レベル50・60・70ダンジョン&quot;,
        ///    &quot;3&quot;: &quot;コンテンツルーレット: メインクエスト&quot;,
        ///    &quot;4&quot;: &quot;コンテンツルーレット: ギルドオーダー&quot;,
        ///    &quot;5&quot;: &quot;コンテンツルーレット: エキスパート&quot;,
        ///    &quot;6&quot;: &quot;コンテンツルーレット: 討伐・討滅戦&quot;,
        ///    &quot;7&quot;: &quot;コンテンツルーレット: フロントライン&quot;,
        ///    &quot;8&quot;: &quot;コンテンツルーレット: レベル80ダンジョン&quot;,
        ///    &quot;9&quot;: &quot;コンテンツルーレット: メンター&quot;,
        ///    &quot;10&quot;: &quot;ザ・フィースト (カジュアルマッチ)&quot;,
        ///    &quot;11&quot;: &quot;ザ・フィースト (カジュアルマッチ)&quot;,
        ///    &quot;13&quot;: &quot;ザ・フィースト (ランクマッチ)&quot;,
        ///    &quot;15&quot;: &quot;コンテンツルーレット: アライアンスレイド&quot;,
        ///    &quot;16&quot;: &quot;ザ・フィースト (チームランクマッチ)&quot;,
        ///    &quot;17&quot;: &quot;コンテンツルーレット: レイド&quot;,
        ///    &quot;18&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dfas_ja {
            get {
                return ResourceManager.GetString("dfas_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;roulettes&quot;: {
        ///    &quot;1&quot;: &quot;무작위 임무: 레벨링&quot;,
        ///    &quot;2&quot;: &quot;무작위 임무: 레벨 50/60/70 던전&quot;,
        ///    &quot;3&quot;: &quot;무작위 임무: 주요 퀘스트&quot;,
        ///    &quot;4&quot;: &quot;무작위 임무: 길드 작전&quot;,
        ///    &quot;5&quot;: &quot;무작위 임무: 숙련자&quot;,
        ///    &quot;6&quot;: &quot;무작위 임무: 토벌전&quot;,
        ///    &quot;7&quot;: &quot;무작위 임무: 전장&quot;,
        ///    &quot;8&quot;: &quot;무작위 임무: 레벨 80 던전&quot;,
        ///    &quot;9&quot;: &quot;무작위 임무: 멘토&quot;,
        ///    &quot;10&quot;: &quot;더 피스트 - 친선 경기&quot;,
        ///    &quot;11&quot;: &quot;더 피스트 - 친선 경기&quot;,
        ///    &quot;13&quot;: &quot;더 피스트 - 개인&quot;,
        ///    &quot;15&quot;: &quot;무작위 임무: 24인 레이드&quot;,
        ///    &quot;16&quot;: &quot;더 피스트 - 팀&quot;,
        ///    &quot;17&quot;: &quot;무작위 임무: 레이드&quot;,
        ///    &quot;18&quot;: &quot;초코보 레이스: 사골리길&quot;,
        ///    &quot;19&quot;: &quot;초코보 레이스: 코스타 델 솔&quot;,
        ///    &quot;20&quot;: &quot;초코보 레이스: 트랑킬로&quot;,
        ///    &quot;21&quot;: &quot;초코보 레이스: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dfas_ko {
            get {
                return ResourceManager.GetString("dfas_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifyingglassicon_114513_22 {
            get {
                object obj = ResourceManager.GetObject("magnifyingglassicon_114513-22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Main_Command_52_Icon {
            get {
                object obj = ResourceManager.GetObject("Main_Command_52_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Map64_Icon {
            get {
                object obj = ResourceManager.GetObject("Map64_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # ACT.DFAssist english message
        ///
        ///app-description=DFASSIST for ACT
        ///app-name=DFASSIST
        ///e-setting-load=Error on reading settings: {0}
        ///e-setting-save=Error on saving settings
        ///e-null-data=Null data found: {0}
        ///i-data-version=Read game data (R:{2}/I:{1}/A:{0}/F:{3})
        ///i-matched=Matched [{0}]
        ///i-queue-instance=Start matching [{0}]
        ///i-queue-roulette=Start roulette matching [{0}]
        ///i-selected-color=Selected color is {0}
        ///l-data-error=Error on processing data
        ///l-fate-occured-info=&quot;{0}&quot; spawned!
        ///l-instance-enter=Enter: {0}
        ///l-ins [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mesg_en {
            get {
                return ResourceManager.GetString("mesg_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # ACT.DFAssist にほんご メッセージ
        ///
        ///app-description=ACT用のDFASSISTプラグイン
        ///app-name=DFASSIST
        ///e-setting-load=設定読みにエラー: {0}
        ///e-setting-save=設定保存にエラー
        ///e-null-data=空きデータが見つかりました: {0}
        ///i-data-version=データを読みました (A:{0}/I:{1}/R:{2}/F:{3})
        ///i-matched=準備完了 [{0}]
        ///i-queue-instance=コンテンツ参加申請開始 [{0}]
        ///i-queue-roulette=ルーレット参加申請開始 [{0}]
        ///i-selected-color=選択した色は{0}です
        ///l-data-error= データ処理に問題があります
        ///l-fate-occured-info=&quot;{0}&quot; 発生!
        ///l-instance-enter=入場: {0}
        ///l-instance-leave=退場: {0}
        ///l-plugin-started=プラグイン開始
        ///l-plugin-stopped=プラグイン停止
        ///l-unknown-area=知らない [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mesg_ja {
            get {
                return ResourceManager.GetString("mesg_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # ACT.DFAssist 한국어 메시지
        ///
        ///app-description=ACT에서 쓸 수 있는 DFASSIST 플러그인
        ///app-name=DFASSIST
        ///e-setting-load=설정 읽기 오류: {0}
        ///e-setting-save=설정 저장 오류
        ///e-null-data=빈값이 있습니다: {0}
        ///i-data-version=데이터를 읽었습니다 (A:{0}/I:{1}/R:{2}/F:{3})
        ///i-matched=Queue: 매치 잡힘 [{0}]
        ///i-queue-instance=매치 시작 [{0}]
        ///i-queue-roulette=루렛 시작 [{0}]
        ///i-selected-color=선택한 색깔은 {0}입니다
        ///l-data-error=데이터 처리에 문제가 있습니다
        ///l-fate-occured-info=&quot;{0}&quot; 떳다!
        ///l-instance-enter=들어감: {0}
        ///l-instance-leave=나옴: {0}
        ///l-plugin-started=플러그인 시작
        ///l-plugin-stopped=플러그인 중지
        ///l-unknown-area=모 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mesg_ko {
            get {
                return ResourceManager.GetString("mesg_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player12_Icon {
            get {
                object obj = ResourceManager.GetObject("Player12_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2_Icon {
            get {
                object obj = ResourceManager.GetObject("Player2_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
